name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install base dependencies - Ubuntu
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8

      - name: Check Python linting
        run: |
            flake8 . --count --show-source --statistics
  test:
    runs-on: ${{ matrix.platform }}
    needs: lint
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: [ '3.8', '3.9', '3.10']

    env:
      PY_COLORS: 1

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install base dependencies - Ubuntu
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run -m pytest

      - name: Generate coverage report in XML
        if: matrix.python-version == '3.10'
        run: |
          coverage xml

      - name: Upload coverage report artifact
        if: matrix.python-version == '3.10'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
      
  check-coverage:
      runs-on: ubuntu-latest
      needs: test

      steps:
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Upload coverage report to Codecov
        run: |
            echo "Uploading coverage report..."